"""updated tables

Revision ID: 30b901fdce2f
Revises: 8d7d299e6b53
Create Date: 2025-10-08 21:39:31.746052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b901fdce2f'
down_revision = '8d7d299e6b53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_invoices_stripe_payment_intent_id'), type_='unique')
        batch_op.create_index(batch_op.f('ix_invoices_stripe_payment_intent_id'), ['stripe_payment_intent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_stripe_payment_intent_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_invoices_stripe_payment_intent_id'), ['stripe_payment_intent_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
