"""Auto-generated migration

Revision ID: 3d947f10c97a
Revises: 
Create Date: 2025-09-09 12:35:58.258366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d947f10c97a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_plans')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('clients_plan_id_fkey'), type_='foreignkey')
        batch_op.drop_column('plan_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_value', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('billing_frequency', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('hourly_budget', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('hours_used', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('budget_spent', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('budget_spent')
        batch_op.drop_column('hours_used')
        batch_op.drop_column('hourly_budget')
        batch_op.drop_column('billing_frequency')
        batch_op.drop_column('project_value')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('clients_plan_id_fkey'), 'subscription_plans', ['plan_id'], ['id'])

    op.create_table('subscription_plans',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('tier2_seller_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('billing', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('max_clients', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('subscription_plans_seller_id_fkey')),
    sa.ForeignKeyConstraint(['tier2_seller_id'], ['tier2_sellers.id'], name=op.f('subscription_plans_tier2_seller_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subscription_plans_pkey'))
    )
    # ### end Alembic commands ###
