"""schema update

Revision ID: 5885f6964a81
Revises: 612d64c9f4c1
Create Date: 2025-09-29 15:35:59.293828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5885f6964a81'
down_revision = '612d64c9f4c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_admin_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('created_by_tier1_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('admin_commission_pct', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tier1_commission_pct', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.drop_constraint(batch_op.f('subscription_plans_admin_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tier1_sellers', ['created_by_tier1_id'], ['id'])
        batch_op.create_foreign_key(None, 'admins', ['created_by_admin_id'], ['id'])
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subscription_plans_admin_id_fkey'), 'admins', ['admin_id'], ['id'])
        batch_op.drop_column('tier1_commission_pct')
        batch_op.drop_column('admin_commission_pct')
        batch_op.drop_column('created_by_tier1_id')
        batch_op.drop_column('created_by_admin_id')

    # ### end Alembic commands ###
