"""update

Revision ID: 612d64c9f4c1
Revises: 52d46bdfbd27
Create Date: 2025-09-24 12:24:12.480531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612d64c9f4c1'
down_revision = '52d46bdfbd27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('intake_form_completed')

    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan_id', sa.String(length=36), nullable=False))
        batch_op.alter_column('tier1_seller_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('tier2_seller_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('admin_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('tier1_commission_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
        batch_op.alter_column('admin_commission_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('commissions_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'subscription_plans', ['subscription_plan_id'], ['id'])
        batch_op.drop_column('project_id')

    with op.batch_alter_table('project_billing', schema=None) as batch_op:
        batch_op.drop_column('billing_mode')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'subscription_plans', ['subscription_plan_id'], ['id'])
        batch_op.drop_column('project_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_value', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subscription_plan_id')

    with op.batch_alter_table('project_billing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_mode', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('commissions_project_id_fkey'), 'projects', ['project_id'], ['id'])
        batch_op.alter_column('admin_commission_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('tier1_commission_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('admin_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('tier2_seller_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('tier1_seller_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('subscription_plan_id')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intake_form_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
