"""Add Stripe and billing schedule fields

Revision ID: 8d7d299e6b53
Revises: dd5ff839543d
Create Date: 2025-10-07 17:13:16.235108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7d299e6b53'
down_revision = 'dd5ff839543d'
branch_labels = None
depends_on = None


# In migrations/versions/8d7d299e6b53_....py

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
        # Giving the constraint a specific name is good practice
        batch_op.create_unique_constraint('uq_invoices_stripe_payment_intent_id', ['stripe_payment_intent_id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        # --- THIS IS THE FIX ---
        # Provides default values for existing rows to prevent the error.
        batch_op.add_column(sa.Column('billing_day_of_month', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('next_billing_date', sa.Date(), nullable=False, server_default=sa.text('now()')))
        # --- END OF FIX ---
        
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)

    with op.batch_alter_table('tier1_sellers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_account_id', sa.String(length=255), nullable=True))

    with op.batch_alter_table('tier2_sellers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_account_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tier2_sellers', schema=None) as batch_op:
        batch_op.drop_column('stripe_account_id')

    with op.batch_alter_table('tier1_sellers', schema=None) as batch_op:
        batch_op.drop_column('stripe_account_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('next_billing_date')
        batch_op.drop_column('billing_day_of_month')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('stripe_payment_intent_id')

    # ### end Alembic commands ###
