"""update

Revision ID: dd5ff839543d
Revises: 5885f6964a81
Create Date: 2025-09-29 16:27:30.017517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5ff839543d'
down_revision = '5885f6964a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_billing', schema=None) as batch_op:
        batch_op.drop_column('commission_id')

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('creator_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('parent_plan_id', sa.String(length=36), nullable=True))
        batch_op.drop_constraint(batch_op.f('subscription_plans_created_by_tier1_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('subscription_plans_created_by_admin_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'subscription_plans', ['parent_plan_id'], ['id'])
        batch_op.drop_column('created_by_admin_id')
        batch_op.drop_column('created_by_tier1_id')

    with op.batch_alter_table('tier1_sellers', schema=None) as batch_op:
        batch_op.drop_column('commission_value')
        batch_op.drop_column('commission_type')

    with op.batch_alter_table('tier2_sellers', schema=None) as batch_op:
        batch_op.drop_column('commission_value')
        batch_op.drop_column('commission_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tier2_sellers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('commission_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))

    with op.batch_alter_table('tier1_sellers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('commission_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_tier1_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_by_admin_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subscription_plans_created_by_admin_id_fkey'), 'admins', ['created_by_admin_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('subscription_plans_created_by_tier1_id_fkey'), 'tier1_sellers', ['created_by_tier1_id'], ['id'])
        batch_op.drop_column('parent_plan_id')
        batch_op.drop_column('creator_type')
        batch_op.drop_column('creator_id')

    with op.batch_alter_table('project_billing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
